if: tag IS blank
language: node_js
script: npm run build

stages:
  - name: publish
    if: branch = master && type != pull_request

jobs:
  include:
    - stage: publish
      node_js: node
      script:
        - npm build
        - git remote set-url origin https://${GITHUB_TOKEN}@github.com/CodeRevolver/react-components.git
        - git checkout ${TRAVIS_BRANCH}
        - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
        - npm publish --access public
        - npm run styleguide:build
      deploy:
        - provider: pages
          skip-cleanup: true
          github-token: $GITHUB_TOKEN
          github_token: $GITHUB_TOKEN
          local-dir: docs
          on:
            branch: master