if: tag IS blank
language: node_js
node_js:
  - "lts/*"
  - "node"
script: npm run ci

stages:
  - test
  - name: publish
    if: branch = master && type != pull_request

jobs:
  include:
    - stage: publish
      node_js: node
      script:
        - npm ci
        - git remote set-url origin https://${GITHUB_TOKEN}@github.com/CodeRevolver/react-components.git
        - git checkout ${TRAVIS_BRANCH}
        - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
        - npx lerna publish --conventional-commits --changelog-preset eslint --yes
        - sh rebuild-docs.sh
      deploy:
        - provider: pages
          skip-cleanup: true
          github-token: $GITHUB_TOKEN
          keep-history: true
          local-dir: ./docs